TRAINING_TEXTS = [
    "I can't believe you did all this for me! The candles, the soft music, it's absolutely magical. It's like you've brought my dreams to life. I've never felt so cherished and understood before.",
    "Well, I wanted tonight to be special. You deserve nothing less. Ever since we first met, you've brought so much joy into my life. This is just a small way to show you how much you mean to me.",
    "You're making me blush! But truly, this is beyond anything I could have imagined. It's been a long time since I've felt this happy, and it's all thanks to you. I was beginning to think moments like this only happened in fairy tales.",
    "Sometimes, reality can be even better than dreams. Being with you has shown me that. Every moment we spend together feels like a gift. I wanted to create a memory that we could both cherish.",
    "Well, you've certainly succeeded. This is a night I'll never forget. But it's not just about the setting or the atmosphere; it's about being here with you. That's what makes it truly special.",
    "You have no idea how much that means to me. I've been wanting to tell you something for a while now. Being around you makes everything feel right, like I've finally found where I belong.",
    "I feel the same way. It's like our paths were always meant to cross. You bring out the best in me, and I can't help but smile when I'm with you.",
    "Do you remember the first time we met? I was so nervous, stumbling over my words, but you just laughed and made me feel at ease.",
    "Of course I remember! You were trying to ask for directions but ended up inviting me to coffee instead. It was the most endearing thing."
]
"""
    "I thought I'd completely embarrassed myself, but then you said yes, and I felt like the luckiest person alive.",
    "And here we are now, sharing this incredible evening. It's amazing how one chance encounter can change everything.",
    "It's true. Life has a funny way of bringing people together. I can't imagine what things would be like if we hadn't met that day.",
    "Neither can I. You've become such an important part of my life in such a short time. Sometimes it feels like I've known you forever.",
    "I know exactly what you mean. It's like our souls recognize each other. Maybe that's a bit cheesy, but it's how I feel.",
    "Cheesy can be good sometimes. Besides, I happen to like cheese—both the dairy and the sentimental kinds.",
    "Well then, here's to embracing all the cheesy moments together. May there be many more to come.",
    "Agreed! So, tell me more about what inspired all of this tonight. It's so thoughtful and intricate.",
    "I wanted to create a space where we could just be ourselves, away from all the noise and distractions. A place where we could talk and really connect.",
    "You've definitely accomplished that. I feel like I can tell you anything. There's a comfort and openness between us that I've never experienced before.",
    "That's all I've ever wanted. To be someone you can rely on, someone you can share your dreams and fears with.",
    "You are that person for me. And I hope I can be the same for you.",
    "You already are. More than you know. You've helped me see the world differently, in brighter colors and with more hope.",
    "It's amazing how love can do that, isn't it? It transforms everything.",
    "Did you just say... love?",
    "I did. And I meant it. I love you.",
    "I... I love you too. I've been wanting to tell you for so long, but I was afraid it was too soon.",
    "There's no such thing as too soon when it's right. And with you, it feels so right.",
    "You've just made me the happiest person in the world.",
    "And you've done the same for me. Here's to us and the beautiful journey ahead.",
    "To us. May this be the first of many unforgettable nights together.",
    "Absolutely. Now, shall we dance? The music is too lovely to ignore.",
    "I'd love to. Lead the way.",
    "With pleasure. Just follow my lead and let the music guide us.",
    "You know, I've never been much of a dancer, but with you, I feel like I can do anything.",
    "That's because we're in sync. Just trust yourself—and me.",
    "I do. Completely.",
    "Good. Now, let's make this a night to remember.",
    "Every moment with you is unforgettable.",
    "You're quite the charmer, aren't you?",
    "Only when I'm inspired. And you, my dear, are a constant source of inspiration.",
    "You're going to give me a big head with all these compliments.",
    "Well, it's a risk I'm willing to take. You deserve to know how wonderful you are.",
    "Thank you. That means more to me than you know.",
    "Anytime. Now, how about we make a wish upon that beautiful star up there?",
    "I think that's a lovely idea. What should we wish for?",
    "Anything your heart desires.",
    "Alright. But I have a feeling my wish might have already come true.",
    "Mine too. But it doesn't hurt to dream even bigger.",
    "True. Okay, let's close our eyes and make a wish.",
    "Done. Now, let's see where fate takes us.",
    "I'm excited to find out, as long as we're together.",
    "Always.",
    "Did you hear that sound coming from upstairs? It sounded like footsteps.",
    "Yeah, but everyone else is asleep. It can't be any of them.",
    "Exactly, which is why I'm starting to freak out a little. Maybe we should check it out.",
    "Are you serious? You want to go toward the creepy noise?",
    "Well, we can't just ignore it. What if someone broke in?",
    "Alright, fine. But we're sticking together, and I'm grabbing this fireplace poker just in case.",
    "Good idea. I'll take the heavy flashlight. Let's go.",
    "The hallway lights are flickering. That's not a good sign.",
    "Tell me about it. This feels like a scene straight out of a horror movie.",
    "Shh, listen. The noise is coming from the attic now.",
    "I didn't even know we had an attic. Are you sure you want to do this?",
    "No, but we have to. The attic door is slightly open.",
    "Okay, on the count of three, we push it open and shine the light inside.",
    "One... two... three!",
    "There's nothing here but old furniture and boxes.",
    "Wait, what's that in the corner? It looks like a shadow moving.",
    "Who's there? Show yourself!",
    "Well, aren't you two brave souls venturing into the darkness.",
    "Who said that? Come out where we can see you!",
    "I've been waiting for someone to find me. It's been so lonely up here.",
    "This isn't funny anymore. If this is a prank, it's gone too far.",
    "Oh, it's no prank. The real fun is just beginning.",
    "We need to get out of here right now!",
    "There is no right or wrong here. Only the inevitable.",
    "I refuse to accept that! There has to be a way out!",
    "Your determination is amusing.",
    "Look, if we can't escape physically, maybe we can outsmart it.",
    "How?",
    "By not giving in to fear. Maybe that's what it feeds on.",
    "Interesting theory, but will it save you?",
    "We're not afraid of you!",
    "Your trembling hands say otherwise.",
    "Fine, maybe we are scared, but that doesn't mean we'll give up.",
    "Such spirit. Perhaps I'll let you go, for now.",
    "Wait, really?",
    "The door is open! Let's go!",
    "Don't look back. Just run!",
    "Until next time. We'll meet again.",
    "We made it! The door closed behind us!",
    "I can't believe that actually worked.",
    "Let's get out of this house. Now.",
    "Agreed. And we're never coming back.",
    "I just don't understand why you did it. After everything we've been through, how could you betray me like this?",
    "I didn't mean for it to happen. It just did. I was confused and things got out of control.",
    "Confused? That's your excuse? You hurt me and you think 'confusion' justifies it?",
    "I'm sorry! I know I messed up, but please believe me when I say it wasn't intentional.",
    "Sorry doesn't fix this. You shattered my trust, and I don't know if I can ever forgive you.",
    "Please, give me a chance to make it right. I can't stand the thought of losing you over a mistake.",
    "A mistake? You call deliberate lies and deceit a mistake? I feel like I don't even know who you are anymore.",
    "I know you're angry, and you have every right to be. But I'm still the same person. Let me explain.",
    "Explain what? How you kept secrets from me? How you looked me in the eyes and lied?",
    "It wasn't like that! I was trying to protect you from getting hurt.",
    "Well, congratulations, you failed miserably. I'm more hurt now than I ever was.",
    "I never wanted this. I thought I was doing the right thing at the time.",
    "The right thing? For whom? Certainly not for me.",
    "I see now that I was wrong. I wish I could go back and change everything.",
    "But you can't. And now we're here, with everything broken between us.",
    "Is there any way we can fix this? I'm willing to do whatever it takes.",
    "I don't know. I need time to think. Right now, all I feel is anger and disappointment.",
    "I understand. Take all the time you need. Just please, don't shut me out completely.",
    "I can't make any promises. Trust isn't something that can be easily repaired.",
    "I realize that. But I hope someday you'll find it in your heart to forgive me.",
    "We'll see. But for now, I think it's best if we keep our distance.",
    "If that's what you want, I won't push. Just know that I'm here if you decide to talk.",
    "Goodbye.",
    "Hey man, did you catch that new action movie everyone's talking about?",
    "Not yet. Is it really that good?",
    "Oh, it's amazing! I actually got to see it at a special preview last week.",
    "Special preview? How'd you manage that?",
    "I've got some connections in the industry, you know. Perks of knowing the right people.",
    "Impressive. Maybe next time you can hook me up with a ticket.",
    "Yeah, sure. I can make that happen. VIP treatment and all.",
    "Haha, sounds great. So, what was the best part of the movie?",
    "Honestly, the stunts were next level. But I don't want to spoil anything for you.",
    "Appreciated. I'll try to watch it this weekend.",
    "Let me know when you do. Maybe we can grab a coffee afterward and discuss.",
    "Sounds like a plan. By the way, how's your new job going?",
    "Oh, it's going well. They're already talking about promoting me.",
    "Wow, that was fast. Congrats!",
    "Thanks! But you know, I always aim high.",
    "Good for you. Keep up the hard work.",
    "Will do. Anyway, I've got to head out. Got a meeting with some important folks.",
    "Alright, catch you later.",
    "See you soon."
]
"""