CONFUSED_SCARED_ANGRY = [
    "I can't believe you hid this from me all this time. We've been friends for years, and you didn't think to tell me something this important? It feels like I don't even know who you are anymore. Why would you keep me in the dark?",
    "It's not that simple. I was confused and scared about the whole situation. I didn't know how to bring it up without causing more problems. Every day I wanted to tell you, but the words just wouldn't come out. I'm so sorry for making you feel this way.",
    "You were scared? Imagine how I feel now! I'm angry, hurt, and utterly baffled. I thought we told each other everything. This isn't just a small secret; it's something that affects both of us deeply. How could you think keeping silent was the best option?",
    "I know I messed up, and I regret it more than you can imagine. I was trying to protect you, but I see now that I only made things worse. I was overwhelmed and didn't want to drag you into my mess. Please believe me when I say I never meant to hurt you.",
    "It's hard to trust you right now. I'm not sure if I can just move past this. Part of me wants to forgive you, but another part is too hurt to even consider it. I need time to process everything that's happened.",
    "I understand. Take all the time you need. Just know that I'm here, ready to talk whenever you're ready. I value our friendship more than anything, and I'm willing to do whatever it takes to make things right between us.",
    "I appreciate that, but actions speak louder than words. If you truly want to fix this, you'll have to prove that I can trust you again. It's not going to be easy, and it won't happen overnight.",
    "I accept that. I'll do whatever it takes, no matter how long it takes. You're too important to me to lose over a mistake that I deeply regret. Please give me a chance to make amends.",
    "We'll see. For now, I think it's best if we keep some distance. I need to sort out my feelings without any added pressure. Maybe in time, things will become clearer for both of us.",
    "Alright. I'll respect your wishes and give you space. Just remember that I'm here if you need anything at all. I hope one day you'll find it in your heart to forgive me.",
    "Only time will tell. Let's leave it at that for now."
]


FEAR = [
    "Did anyone else feel that chill just now? It's like the temperature dropped ten degrees all of a sudden.",
    "Yeah, and the lights keep flickering. I knew we shouldn't have come to this abandoned house.",
    "Come on, guys, it's just an old place. Don't tell me you're scared of a few creaky floors and drafty rooms.",
    "I'm telling you, something doesn't feel right. Ever since we walked in, I've had this uneasy feeling.",
    "Wait, do you hear that? It sounds like... whispering.",
    "Whispering? Stop trying to freak us out. It's probably just the wind blowing through the cracks.",
    "No, listen carefully. It's coming from the hallway.",
    "You're right. It's like someone is muttering just out of earshot.",
    "Okay, that's enough. Let's get out of here. This isn't funny anymore.",
    "I agree. We should leave while we still can.",
    "Too late for that. The door won't open!",
    "What do you mean it won't open? Let me try.",
    "It's stuck, or locked from the outside. How is that possible?",
    "I don't know, but we need to find another way out.",
    "Hello there. Looking for something?",
    "Who said that? Show yourself!",
    "I'm right here. Didn't mean to startle you.",
    "Who are you? How did you get in here?",
    "Oh, I've always been here. This is my home, after all.",
    "Your home? But this place has been abandoned for years.",
    "Abandoned? No, not at all. I've been taking care of it quite nicely.",
    "Listen, we didn't mean to trespass. We'll just leave now.",
    "I'm afraid I can't let you do that. You see, guests are so rare these days.",
    "What do you want from us?",
    "Just some company. It's been so lonely here.",
    "Guys, we need to find a way out. Now.",
    "There's a window in the next room. Maybe we can break it.",
    "Trying to leave so soon? But the fun is just beginning.",
    "Stay away from us!",
    "Why the fear? I only wish to play a game.",
    "We're not interested in any games. Let us go!",
    "But where's the excitement in that? Let's make this interesting.",
    "I don't like this. He's blocking the way!",
    "We can take him together. On the count of three.",
    "One... two... three!",
    "Ah, bravery. Such a fleeting virtue.",
    "He moved so fast! How did he get behind us?",
    "Didn't expect that, did you? Now, shall we continue?",
    "Please, just tell us what you want!",
    "I already told you. Entertainment. Let's see how well you handle fear.",
    "We're not playing your twisted games!",
    "Oh, but you already are. The moment you stepped inside, the game began.",
    "What do we do now?",
    "Stick together. Don't let him separate us.",
    "Wise choice, but it won't help. This house has a mind of its own.",
    "The walls... they're closing in!",
    "Impossible! Houses don't just shift like this!",
    "In here, anything is possible. Welcome to my world.",
    "This can't be happening!",
    "Believe me, it's very real. And it's only going to get more interesting."
]


ROMANCE = [
    "I can't believe you did all this for me! The candles, the soft music, it's absolutely magical. It's like you've brought my dreams to life. I've never felt so cherished and understood before.",
    "Well, I wanted tonight to be special. You deserve nothing less. Ever since we first met, you've brought so much joy into my life. This is just a small way to show you how much you mean to me.",
    "You're making me blush! But truly, this is beyond anything I could have imagined. It's been a long time since I've felt this happy, and it's all thanks to you. I was beginning to think moments like this only happened in fairy tales.",
    "Sometimes, reality can be even better than dreams. Being with you has shown me that. Every moment we spend together feels like a gift. I wanted to create a memory that we could both cherish.",
    "Well, you've certainly succeeded. This is a night I'll never forget. But it's not just about the setting or the atmosphere; it's about being here with you. That's what makes it truly special.",
    "You have no idea how much that means to me. I've been wanting to tell you something for a while now. Being around you makes everything feel right, like I've finally found where I belong.",
    "I feel the same way. It's like our paths were always meant to cross. You bring out the best in me, and I can't help but smile when I'm with you.",
    "Do you remember the first time we met? I was so nervous, stumbling over my words, but you just laughed and made me feel at ease.",
    "Of course I remember! You were trying to ask for directions but ended up inviting me to coffee instead. It was the most endearing thing.",
    "I thought I'd completely embarrassed myself, but then you said yes, and I felt like the luckiest person alive.",
    "And here we are now, sharing this incredible evening. It's amazing how one chance encounter can change everything.",
    "It's true. Life has a funny way of bringing people together. I can't imagine what things would be like if we hadn't met that day.",
    "Neither can I. You've become such an important part of my life in such a short time. Sometimes it feels like I've known you forever.",
    "I know exactly what you mean. It's like our souls recognize each other. Maybe that's a bit cheesy, but it's how I feel.",
    "Cheesy can be good sometimes. Besides, I happen to like cheese—both the dairy and the sentimental kinds.",
    "Well then, here's to embracing all the cheesy moments together. May there be many more to come.",
    "Agreed! So, tell me more about what inspired all of this tonight. It's so thoughtful and intricate.",
    "I wanted to create a space where we could just be ourselves, away from all the noise and distractions. A place where we could talk and really connect.",
    "You've definitely accomplished that. I feel like I can tell you anything. There's a comfort and openness between us that I've never experienced before.",
    "That's all I've ever wanted. To be someone you can rely on, someone you can share your dreams and fears with.",
    "You are that person for me. And I hope I can be the same for you.",
    "You already are. More than you know. You've helped me see the world differently, in brighter colors and with more hope.",
    "It's amazing how love can do that, isn't it? It transforms everything.",
    "Did you just say... love?",
    "I did. And I meant it. I love you.",
    "I... I love you too. I've been wanting to tell you for so long, but I was afraid it was too soon.",
    "There's no such thing as too soon when it's right. And with you, it feels so right.",
    "You've just made me the happiest person in the world.",
    "And you've done the same for me. Here's to us and the beautiful journey ahead.",
    "To us. May this be the first of many unforgettable nights together.",
    "Absolutely. Now, shall we dance? The music is too lovely to ignore.",
    "I'd love to. Lead the way.",
    "With pleasure. Just follow my lead and let the music guide us.",
    "You know, I've never been much of a dancer, but with you, I feel like I can do anything.",
    "That's because we're in sync. Just trust yourself—and me.",
    "I do. Completely.",
    "Good. Now, let's make this a night to remember.",
    "Every moment with you is unforgettable.",
    "You're quite the charmer, aren't you?",
    "Only when I'm inspired. And you, my dear, are a constant source of inspiration.",
    "You're going to give me a big head with all these compliments.",
    "Well, it's a risk I'm willing to take. You deserve to know how wonderful you are.",
    "Thank you. That means more to me than you know.",
    "Anytime. Now, how about we make a wish upon that beautiful star up there?",
    "I think that's a lovely idea. What should we wish for?",
    "Anything your heart desires.",
    "Alright. But I have a feeling my wish might have already come true.",
    "Mine too. But it doesn't hurt to dream even bigger.",
    "True. Okay, let's close our eyes and make a wish.",
    "Done. Now, let's see where fate takes us.",
    "I'm excited to find out, as long as we're together.",
    "Always."
]


NORMAL = [
    "Hey man, did you catch that new action movie everyone's talking about?",
    "Not yet. Is it really that good?",
    "Oh, it's amazing! I actually got to see it at a special preview last week.",
    "Special preview? How'd you manage that?",
    "I've got some connections in the industry, you know. Perks of knowing the right people.",
    "Impressive. Maybe next time you can hook me up with a ticket.",
    "Yeah, sure. I can make that happen. VIP treatment and all.",
    "Haha, sounds great. So, what was the best part of the movie?",
    "Honestly, the stunts were next level. But I don't want to spoil anything for you.",
    "Appreciated. I'll try to watch it this weekend.",
    "Let me know when you do. Maybe we can grab a coffee afterward and discuss.",
    "Sounds like a plan. By the way, how's your new job going?",
    "Oh, it's going well. They're already talking about promoting me.",
    "Wow, that was fast. Congrats!",
    "Thanks! But you know, I always aim high.",
    "Good for you. Keep up the hard work.",
    "Will do. Anyway, I've got to head out. Got a meeting with some important folks.",
    "Alright, catch you later.",
    "See you soon."
]

HAPPY = [
    "Hey, I just wanted to take a moment to tell you how grateful I am for everything you've done. Your support has really made a difference in my life.",
    "Oh, it's no problem at all! I'm happy to help whenever I can. Seeing you happy makes me happy too.",
    "Seriously, though, you went above and beyond. Remember when I was overwhelmed with that project? You stepped in without me even asking and stayed late to help me finish it. I don't know what I would have done without you.",
    "Well, I could tell you were stressed, and I didn't want you to go through it alone. Plus, working together made it more enjoyable for both of us, don't you think?",
    "Absolutely! It reminded me of why we're such good friends. You always know how to make tough situations better. I'm really lucky to have you in my life.",
    "And I'm lucky to have you too. You've been there for me countless times. Like when I was nervous about that job interview, and you helped me prepare. I couldn't have done it without your encouragement.",
    "We make a pretty great team, don't we? By the way, I was thinking we should celebrate all our recent successes. How about we plan a fun weekend getaway?",
    "That sounds fantastic! I've been itching to take a break and relax somewhere nice. Do you have any places in mind?",
    "Actually, I was looking into that cozy cabin by the lake we've always talked about. We could go hiking, have a barbecue, and just unwind.",
    "Oh, I love that idea! Being in nature sounds perfect right now. Let's do it! I'll check my schedule and we can set a date.",
    "Great! I'm already excited about it. It'll be nice to disconnect from everything and just enjoy some good company.",
    "Agreed. You know, moments like these make me realize how important friendship is. I can't imagine navigating life's ups and downs without you.",
    "I feel the same way. You've brought so much joy and positivity into my life. Here's to many more adventures together!",
    "Cheers to that! And who knows, maybe we'll discover some new hobbies or interests on this trip.",
    "That would be awesome. Maybe we'll even try our hand at fishing or kayaking.",
    "Haha, I can already picture us struggling to catch a fish. But it would make for some great stories!",
    "Definitely! It's not about being experts; it's about having fun and making memories.",
    "Exactly. So, let's make a list of things we want to do and start planning.",
    "Sounds good. I'll bring the snacks and you handle the playlist?",
    "Deal! This is going to be an unforgettable trip.",
    "I can't wait. Thanks again for suggesting it. You always know how to brighten my day.",
    "Anytime! That's what friends are for, right?"
]

SAD = [
    "I still can't wrap my head around it. Just two days ago, we were all laughing and planning our next hiking trip. Now, he's gone forever.",
    "I know. The news of the car accident hit me like a ton of bricks. It's so hard to believe that a drunk driver took his life just like that.",
    "He had so much ahead of him. Remember how excited he was about starting his new job next month? He couldn't stop talking about it.",
    "Yeah, he was finally getting to pursue his passion. It's so unfair that he won't get to live out his dreams.",
    "I keep replaying our last conversation in my head. I wish I had told him how much his friendship meant to me.",
    "I'm sure he knew. You two were inseparable. He always spoke about how much he valued your bond.",
    "It's just that I feel this immense guilt. Like there was something I could have done to prevent it.",
    "Don't blame yourself. None of us could have foreseen this tragedy. It was a senseless act by someone else's negligence.",
    "I went by his parents' house earlier. They are devastated. His mom couldn't stop crying, and his dad just stared blankly at the wall.",
    "That breaks my heart. Maybe we can organize something to honor his memory, like a memorial service or a fundraiser for drunk driving awareness.",
    "That's a great idea. He was always passionate about helping others. It would be a fitting tribute.",
    "Do you remember how he volunteered every weekend at the community center? He truly had a heart of gold.",
    "Absolutely. He touched so many lives with his kindness. The turnout for his memorial will probably be huge.",
    "I hope so. It might bring some comfort to his family to see how loved he was by everyone.",
    "We should gather all the photos and videos we have of him to share at the service.",
    "Yes, let's do that. It'll be painful but also healing to remember the good times.",
    "He wouldn't want us to be sad forever. He always found a way to make us smile, even in the toughest times.",
    "You're right. Maybe we can find strength in that. He lived his life fully, and we should strive to do the same in his honor.",
    "It's going to be hard, but at least we have each other to lean on.",
    "Exactly. We'll get through this together, just like he would have wanted us to."
]

percentage_of_data = 0.05

# Create new arrays with the percentage of data
CONFUSED_SCARED_ANGRY = CONFUSED_SCARED_ANGRY[:int(len(CONFUSED_SCARED_ANGRY) * percentage_of_data)]
FEAR = FEAR[:int(len(FEAR) * percentage_of_data)]
ROMANCE = ROMANCE[:int(len(ROMANCE) * percentage_of_data)]
NORMAL = NORMAL[:int(len(NORMAL) * percentage_of_data)]
HAPPY = HAPPY[:int(len(HAPPY) * percentage_of_data)]
SAD = SAD[:int(len(SAD) * percentage_of_data)]

# Combine the shortened arrays
TRAINING_TEXTS = CONFUSED_SCARED_ANGRY + FEAR + ROMANCE + NORMAL + HAPPY + SAD